### ISSUE TITLE
ACDC database

### ISSUE THREAD

**Issue by MB-Mtl** [julien-zheng/CardiacSegmentationPropagation#1]
Excellent project, Julien.

Any chance you could supply the ACDC formatted scripts?

Many thanks!

**Comment by julien-zheng** [comment]
Hello,

Thanks a lot for your interest! So sorry for the super long delay to answer your question! 

As indicated on the web-page of ACDC (https://www.creatis.insa-lyon.fr/Challenge/acdc/databases.html), personal registration is required to access the dataset. Hence it would be necessary to register and then download the dataset yourself to see any related script.

Best,
Julien
